import type { Config } from "tailwindcss";

// Theme copied verbatim from the approved Stitch export (design/stitch/*/code.html),
// which renders with the Tailwind 3.4.17 Play CDN. Keep this in sync with the design
// rather than editing tokens here; DESIGN.md documents their intent.
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container": "#201f22",
        "on-primary-fixed-variant": "#5516be",
        "on-surface": "#e5e1e4",
        "surface-bright": "#39393b",
        error: "#ffb4ab",
        "outline-variant": "#494454",
        outline: "#958ea0",
        "inverse-primary": "#6d3bd7",
        "tertiary-fixed-dim": "#4edea3",
        tertiary: "#4edea3",
        "surface-tint": "#d0bcff",
        "tertiary-container": "#00a572",
        "secondary-container": "#03b5d3",
        "on-tertiary-container": "#00311f",
        "on-tertiary": "#003824",
        "error-container": "#93000a",
        "on-secondary-fixed-variant": "#004e5c",
        "on-secondary-container": "#00424e",
        "on-tertiary-fixed-variant": "#005236",
        "surface-container-highest": "#353437",
        background: "#131315",
        "primary-fixed": "#e9ddff",
        "on-background": "#e5e1e4",
        "on-primary": "#3c0091",
        "secondary-fixed": "#acedff",
        "surface-container-lowest": "#0e0e10",
        "primary-container": "#a078ff",
        "surface-container-low": "#1c1b1d",
        "on-error": "#690005",
        "surface-container-high": "#2a2a2c",
        "on-surface-variant": "#cbc3d7",
        primary: "#d0bcff",
        "tertiary-fixed": "#6ffbbe",
        "on-primary-container": "#340080",
        "inverse-surface": "#e5e1e4",
        "on-primary-fixed": "#23005c",
        "surface-dim": "#131315",
        "secondary-fixed-dim": "#4cd7f6",
        "inverse-on-surface": "#313032",
        "surface-variant": "#353437",
        "primary-fixed-dim": "#d0bcff",
        "on-tertiary-fixed": "#002113",
        "on-error-container": "#ffdad6",
        "on-secondary": "#003640",
        surface: "#131315",
        secondary: "#4cd7f6",
        "on-secondary-fixed": "#001f26",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-sm": "0.5rem",
        margin: "1rem",
        "margin-md": "1.5rem",
        "space-xl": "2rem",
        gutter: "1rem",
        "space-md": "0.75rem",
        "gutter-lg": "1.5rem",
        "margin-lg": "2rem",
        "space-xs": "0.25rem",
        "space-lg": "1.25rem",
      },
      fontFamily: {
        "headline-lg-mobile": ["Geist"],
        "headline-sm": ["Geist"],
        "code-sm": ["JetBrains Mono"],
        "body-lg": ["Geist"],
        display: ["Geist"],
        "code-md": ["JetBrains Mono"],
        "headline-lg": ["Geist"],
        "label-sm": ["JetBrains Mono"],
        "body-sm": ["Geist"],
        "headline-md": ["Geist"],
        "label-md": ["JetBrains Mono"],
        "body-md": ["Geist"],
      },
      fontSize: {
        "headline-lg-mobile": [
          "22px",
          {
            lineHeight: "28px",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
        "headline-sm": [
          "16px",
          {
            lineHeight: "24px",
            letterSpacing: "-0.01em",
            fontWeight: "500",
          },
        ],
        "code-sm": [
          "11px",
          {
            lineHeight: "16px",
            letterSpacing: "0em",
            fontWeight: "400",
          },
        ],
        "body-lg": [
          "15px",
          {
            lineHeight: "24px",
            letterSpacing: "-0.005em",
            fontWeight: "400",
          },
        ],
        display: [
          "36px",
          {
            lineHeight: "44px",
            letterSpacing: "-0.03em",
            fontWeight: "600",
          },
        ],
        "code-md": [
          "13px",
          {
            lineHeight: "20px",
            letterSpacing: "-0.01em",
            fontWeight: "400",
          },
        ],
        "headline-lg": [
          "28px",
          {
            lineHeight: "36px",
            letterSpacing: "-0.025em",
            fontWeight: "600",
          },
        ],
        "label-sm": [
          "10px",
          {
            lineHeight: "14px",
            letterSpacing: "0.06em",
            fontWeight: "500",
          },
        ],
        "body-sm": [
          "12px",
          {
            lineHeight: "18px",
            letterSpacing: "0.005em",
            fontWeight: "400",
          },
        ],
        "headline-md": [
          "20px",
          {
            lineHeight: "28px",
            letterSpacing: "-0.02em",
            fontWeight: "500",
          },
        ],
        "label-md": [
          "11px",
          {
            lineHeight: "16px",
            letterSpacing: "0.04em",
            fontWeight: "500",
          },
        ],
        "body-md": [
          "13px",
          {
            lineHeight: "20px",
            letterSpacing: "0em",
            fontWeight: "400",
          },
        ],
      },
    },
  },
} satisfies Config;
