import { z } from "zod";

/** GET /api/health */
export const HealthResponseSchema = z.object({
  status: z.literal("ok"),
  version: z.string().min(1),
  timestamp: z.iso.datetime(),
});

export type HealthResponse = z.infer<typeof HealthResponseSchema>;

/** Body of every non-2xx API response. */
export const ApiErrorResponseSchema = z.object({
  error: z.object({
    code: z.string().min(1),
    message: z.string(),
  }),
});

export type ApiErrorResponse = z.infer<typeof ApiErrorResponseSchema>;

export const API_ERROR_CODES = {
  AUTOMATION_PERSISTENCE_FAILED: "AUTOMATION_PERSISTENCE_FAILED",
  AUTOMATION_UNAVAILABLE: "AUTOMATION_UNAVAILABLE",
  AUTOMATION_NOT_FOUND: "AUTOMATION_NOT_FOUND",
  AUTOMATION_STALE: "AUTOMATION_STALE",
  AUTOMATION_AGENT_NOT_FOUND: "AUTOMATION_AGENT_NOT_FOUND",
  AUTOMATION_SCHEDULE_PAST: "AUTOMATION_SCHEDULE_PAST",
  AUTOMATION_LIMIT: "AUTOMATION_LIMIT",
  AUTOMATION_ACTIVE: "AUTOMATION_ACTIVE",
  AUTOMATION_INTERRUPTED: "AUTOMATION_INTERRUPTED",
  AUTOMATION_BUSY: "AUTOMATION_BUSY",

  ANALYTICS_INVALID_QUERY: "ANALYTICS_INVALID_QUERY",
  MEMORY_INVALID_REQUEST: "MEMORY_INVALID_REQUEST",
  MEMORY_TOO_LARGE: "MEMORY_TOO_LARGE",
  MEMORY_INVALID_UTF8: "MEMORY_INVALID_UTF8",
  MEMORY_CHANGED_ON_DISK: "MEMORY_CHANGED_ON_DISK",
  MEMORY_INVALID_FILE: "MEMORY_INVALID_FILE",
  MEMORY_READ_FAILED: "MEMORY_READ_FAILED",
  MEMORY_WRITE_FAILED: "MEMORY_WRITE_FAILED",
  FILE_NOT_FOUND: "FILE_NOT_FOUND",
  FILE_ALREADY_EXISTS: "FILE_ALREADY_EXISTS",
  FILE_NOT_REGULAR: "FILE_NOT_REGULAR",
  FILE_TOO_LARGE: "FILE_TOO_LARGE",
  FILE_BINARY: "FILE_BINARY",
  FILE_INVALID_PATH: "FILE_INVALID_PATH",
  FILE_PATH_ESCAPE: "FILE_PATH_ESCAPE",
  FILE_SYMLINK_ESCAPE: "FILE_SYMLINK_ESCAPE",
  FILE_READ_FAILED: "FILE_READ_FAILED",
  FILE_WRITE_FAILED: "FILE_WRITE_FAILED",
  FILE_DELETE_FAILED: "FILE_DELETE_FAILED",
  FILE_MOVE_FAILED: "FILE_MOVE_FAILED",
  FILE_DIRECTORY_NOT_EMPTY: "FILE_DIRECTORY_NOT_EMPTY",
  FILE_DIRECTORY_TOO_LARGE: "FILE_DIRECTORY_TOO_LARGE",
  FILE_CHANGED_ON_DISK: "FILE_CHANGED_ON_DISK",

  ORCHESTRATION_NOT_FOUND: "ORCHESTRATION_NOT_FOUND",
  ORCHESTRATION_ALREADY_STARTED: "ORCHESTRATION_ALREADY_STARTED",
  ORCHESTRATION_INVALID_PLAN: "ORCHESTRATION_INVALID_PLAN",
  ORCHESTRATION_NO_AGENT_AVAILABLE: "ORCHESTRATION_NO_AGENT_AVAILABLE",
  ORCHESTRATION_CANCELLED: "ORCHESTRATION_CANCELLED",
  ORCHESTRATION_REVIEW_FAILED: "ORCHESTRATION_REVIEW_FAILED",
  ORCHESTRATION_ATTEMPT_LIMIT: "ORCHESTRATION_ATTEMPT_LIMIT",
  ORCHESTRATION_PROVIDER_UNAVAILABLE: "ORCHESTRATION_PROVIDER_UNAVAILABLE",
  ORCHESTRATION_EXECUTION_FAILED: "ORCHESTRATION_EXECUTION_FAILED",
  ORCHESTRATION_TASK_CHANGED: "ORCHESTRATION_TASK_CHANGED",
  ORCHESTRATION_TIMED_OUT: "ORCHESTRATION_TIMED_OUT",
  ORCHESTRATION_PERSISTENCE_FAILED: "ORCHESTRATION_PERSISTENCE_FAILED",
  ORCHESTRATION_TASK_MANAGED: "ORCHESTRATION_TASK_MANAGED",
  ORCHESTRATION_SHUTTING_DOWN: "ORCHESTRATION_SHUTTING_DOWN",

  TASK_NOT_ASSIGNED: "TASK_NOT_ASSIGNED",
  TASK_ALREADY_EXECUTING: "TASK_ALREADY_EXECUTING",
  AGENT_BUSY: "AGENT_BUSY",
  PROVIDER_NOT_AUTOMATION_CAPABLE: "PROVIDER_NOT_AUTOMATION_CAPABLE",
  EXECUTION_START_FAILED: "EXECUTION_START_FAILED",
  EXECUTION_NOT_ACTIVE: "EXECUTION_NOT_ACTIVE",
  EXECUTION_TIMED_OUT: "EXECUTION_TIMED_OUT",
  EXECUTION_CANCELLED: "EXECUTION_CANCELLED",
  EXECUTION_INTERRUPTED: "EXECUTION_INTERRUPTED",
  EXECUTION_INVALID_RESULT: "EXECUTION_INVALID_RESULT",
  EXECUTION_AGENT_FAILED: "EXECUTION_AGENT_FAILED",
  EXECUTION_OUTPUT_LIMIT: "EXECUTION_OUTPUT_LIMIT",
  EXECUTION_PERSISTENCE_FAILED: "EXECUTION_PERSISTENCE_FAILED",
  EXECUTION_SHUTTING_DOWN: "EXECUTION_SHUTTING_DOWN",

  PROVIDER_NOT_FOUND: "PROVIDER_NOT_FOUND",
  PROVIDER_UNAVAILABLE: "PROVIDER_UNAVAILABLE",
  PROVIDER_EXECUTABLE_NOT_FOUND: "PROVIDER_EXECUTABLE_NOT_FOUND",
  PROVIDER_DETECTION_FAILED: "PROVIDER_DETECTION_FAILED",
  PROVIDER_AUTH_REQUIRED: "PROVIDER_AUTH_REQUIRED",
  PROVIDER_CONFIGURATION_REQUIRED: "PROVIDER_CONFIGURATION_REQUIRED",
  PROVIDER_LAUNCH_FAILED: "PROVIDER_LAUNCH_FAILED",
  BAD_REQUEST: "BAD_REQUEST",
  TASK_NOT_FOUND: "TASK_NOT_FOUND",
  TASK_INVALID_ID: "TASK_INVALID_ID",
  TASK_INVALID_TITLE: "TASK_INVALID_TITLE",
  TASK_INVALID_DESCRIPTION: "TASK_INVALID_DESCRIPTION",
  TASK_INVALID_TRANSITION: "TASK_INVALID_TRANSITION",
  TASK_AGENT_NOT_FOUND: "TASK_AGENT_NOT_FOUND",
  TASK_ALREADY_ASSIGNED: "TASK_ALREADY_ASSIGNED",
  TASK_PERSISTENCE_FAILED: "TASK_PERSISTENCE_FAILED",

  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  AGENT_NOT_FOUND: "AGENT_NOT_FOUND",
  AGENT_ALREADY_EXISTS: "AGENT_ALREADY_EXISTS",
  AGENT_INVALID_ID: "AGENT_INVALID_ID",
  AGENT_INVALID_NAME: "AGENT_INVALID_NAME",
  AGENT_INVALID_ROLE: "AGENT_INVALID_ROLE",
  AGENT_INVALID_PROVIDER: "AGENT_INVALID_PROVIDER",
  AGENT_ALREADY_RUNNING: "AGENT_ALREADY_RUNNING",
  AGENT_NOT_RUNNING: "AGENT_NOT_RUNNING",
  AGENT_START_FAILED: "AGENT_START_FAILED",
  AGENT_STOP_FAILED: "AGENT_STOP_FAILED",
} as const;

export type ApiErrorCode = (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES];
